spring.datasource.url: jdbc:mysql://localhost:3306/tasklib?serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: update
someParameter:
  value: Some kind of parameter