spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogdb?serverTimezone=UTC
    useJDBCCompliantTimeZoneShift: true
    username: root
    password: testtest
  jpa:
    show_sql: true # в логах видны sql запросы, false в режиме норм работы (show-sql)
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  mail:
    host: smtp.gmail.com
    port: 587
    username: surkov.r.b
    password:  #somepassword(application password generated for your google account)
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
captcha:
  delete_timeout: 60
  random_secret_key_length: 22
  image:
    format: png
    format_string: data:image/png;base64
    text:
      length: 5
      font:
        random_font1: SanSerif
        random_font2: Serif
        random_font3: Monospaced
    width: 103
    height: 56
post_comment:
  min_length: 200
  max_length: 500
post:
  image:
    root_folder: images
    upload_folder: upload
    format: jpg
  body:
    min_length: 500
    max_length: 1000
  title:
    min_length: 10
    max_length: 100
  default_limit_per_page: 10
  announce:
    max_length: 200
user:
  timeout_edit_profile: 3600000 # ms
  password:
    restore_key_length: 45
    restore_pass_message_string: "/login/change-password/"    # + код для восстановления
    restore_message_subject: "Ссылка для восстановление пароля"
    validation_regex: ^(?=.*[a-z])(?=\S+$).{8,}$    # Для тестов используем упрощенный пароль
    # \A(?=\S*?[0-9])(?=\S*?[a-z])(?=\S*?[A-Z])(?=\S*?[@#$%^&+=])\S{8,}\z
    # ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\S+$).{8,}$
  image:
    root_folder: images
    upload_folder: upload
    avatars_folder: avatars
    format: jpg
    upload_timeout_ms: 3600000
    max_size: 5000000 # in bytes #Пока только проверка, ограничение 1 МБ
  email:
    validation_regex: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}"
general_data:
  title: "DevPub"
  subtitle: "Рассказы разработчиков"
  phone: "+7 903 666-44-55"
  email: "mail@mail.ru"
  copyright: "Дмитрий Сергеев"
  copyright_from: "2005"